name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: Enable auto-merge for Dependabot PRs
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: dependencies
          MERGE_RETRIES: 36
          MERGE_RETRY_SLEEP: 10000
          
